In [2]:
import pandas as pd
import glob

In [3]:
# get data file names
path ='airbnb_data/used/'
filenames = glob.glob(path + "*.csv")
data = pd.concat([pd.read_csv(file) for file in filenames])
data.columns
filenames

['airbnb_data/used\\airbnb_august18.csv',
 'airbnb_data/used\\airbnb_august19.csv',
 'airbnb_data/used\\airbnb_december18.csv',
 'airbnb_data/used\\airbnb_february19.csv',
 'airbnb_data/used\\airbnb_january19.csv',
 'airbnb_data/used\\airbnb_july19.csv',
 'airbnb_data/used\\airbnb_june19.csv',
 'airbnb_data/used\\airbnb_march19.csv',
 'airbnb_data/used\\airbnb_may19.csv',
 'airbnb_data/used\\airbnb_november18.csv',
 'airbnb_data/used\\airbnb_october18.csv',
 'airbnb_data/used\\airbnb_september18.csv']

In [4]:
data['id'].unique()
print(len(data['id'].unique()))

only_lisbon = data[data['neighbourhood_group'] == 'Lisboa']
only_lisbon.shape

33006

(202910, 16)

In [5]:
data = pd.read_csv(filenames[2])

In [6]:
data

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,24056,Linda-a-Velha,95163,Patr√≠cia,Oeiras,"Algs, Linda-a-Velha e Cruz Quebrada-Dafundo",38.717143,-9.239672,Private room,84,2,0,NaN,NaN,1,365
1,25659,"Sunny, Alfama Sleeps 3 - Coeur d'Alfama",107347,Ellie,Lisboa,Santa Maria Maior,38.711671,-9.126964,Entire home/apt,60,2,96,2018-11-09,1.70,1,296
2,26993,Small nice apartment in the center,111686,Hans,Lisboa,Avenidas Novas,38.730747,-9.148240,Entire home/apt,80,6,6,2018-07-04,0.06,1,56
3,28066,ear the birds,120855,Vania,Azambuja,Aveiras de Cima,39.146542,-8.915031,Private room,53,1,0,NaN,NaN,1,365
4,29138,Room for rent in shared house,125304,Susana,Lisboa,Areeiro,38.736341,-9.137916,Private room,71,1,0,NaN,NaN,1,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22645,30889414,Lisbon Suite Room,230833590,Elton,Lisboa,Arroios,38.731914,-9.134689,Private room,45,2,0,NaN,NaN,3,350
22646,30889762,Porto Room,230833590,Elton,Lisboa,Arroios,38.733654,-9.135052,Private room,29,3,0,NaN,NaN,3,365
22647,30896903,Wine Inn Studio,193941293,Wine Inn,Sintra,"S.Maria, S.Miguel, S.Martinho, S.Pedro Penaferrim",38.795981,-9.392228,Entire home/apt,60,1,0,NaN,NaN,7,344
22648,30900839,Welcome to real original Lisbon,201644472,Paulo,Lisboa,Beato,38.732784,-9.107065,Entire home/apt,49,2,0,NaN,NaN,5,365
22649,30902914,Lisbon garden graca,204428759,Cynthia,Lisboa,So Vicente,38.716376,-9.127670,Entire home/apt,54,2,0,NaN,NaN,1,352